mp:
  jwt:
    verify:
      publickey:
        location: /META-INF/publickey.pem
      issuer: https://example.com/issuer
smallrye:
  jwt:
    sign:
      key-location: /META-INF/privatekey.pem
  
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: docker
    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus-demo
  hibernate-orm:
    database:
      generation: 
        create-schemas: false
    log:
      sql: true
      format-sql: true
  flyway:
    migrate-at-start: true
  swagger-ui:
    always-include: true
    path: /swagger

"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        driver: org.testcontainers.jdbc.ContainerDatabaseDriver
        url: jdbc:tc:postgresql:latest:///quarkus-demo
    hibernate-orm:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      database:
        generation:
          create-schemas: false